export const QUIZ_LIST_MODAL_WIDTH = '25vw';
export const QUIZ_LIST_MODAL_HEIGHT = '66vh';

export const QUIZ_INFO_MODAL_WIDTH_REM = 13;
export const QUIZ_INFO_MODAL_CONTAINER_WIDTH_REM = QUIZ_INFO_MODAL_WIDTH_REM + 2;

export const MUSIC_QUIZ_INFO_MODAL_THUMBNAIL_WIDTH_PX = 210;
export const MUSIC_QUIZ_INFO_MODAL_THUMBNAIL_HEIGHT_PX = MUSIC_QUIZ_INFO_MODAL_THUMBNAIL_WIDTH_PX / 2;
